name: vgrnn_env
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=2.1.0
  - nvidia::cuda-toolkit=12.1
  - pyg
  - networkx
  - scikit-learn
  - numpy
  - pip
  - pip:
      - torch-scatter
      - torch-geometric-temporal