model:
  name: topoGED
  node2vec_setup:
    node2vec_dimensions: 64 # We add features onto the end since Node2Vec doesn't embed features
    node2vec_walk_length: 50 # Number of nodes visited per walk (Higher is more global, smaller is local)
    node2vec_num_walks: 10 # Number of walks to start per node (Higher is more detailed and stable)
    node2vec_p: 1.0 # Return parameter, the likelihood of revisiting a node (Higher is less backtracking)
    node2vec_q: 1.0 # The walk bias for determining direction (Higher is more DFS-like; lower is BFS-like)
    node2vec_window: 10 # The context size (Higher is broader learning)
    node2vec_min_count: 1 # Minimum number of occurrences for a node to be considered (Higher will ignore more rare nodes)
    node2vec_batch_words: 4 # The batch size for when Word2Vec is used (Higher will train faster; but with more memory)
    node2vec_workers: 1 # Number of workers (threads)

training:
  batch_size: 64
  lr: 0.001
  epochs: 500

dataset: CollegeMsg
